README Typo
opencontainers/oci-conformance pull request #89
Opened 2022-02-11 16:17 UTC by bowlofstew

This merge request (MR) corrects a typo in the README document.

2022-02-11 16:22 UTC, jdolitsky submitted a review, later dismissed
Can you fix the DCO error?

2022-02-11 16:46 UTC, vsoch approved these changes

2022-02-11 21:17 UTC, sudo-bmitch approved these changes

2022-02-11 21:19 UTC, sudo-bmitch requested changes
Woops, I jumped on the approve before seeing the DCO.

2022-08-13 22:23 UTC, vsoch commented
@bowlofstew would you care to push again with a signed commit?

2022-08-14 02:17 UTC, sudo-bmitch approved these changes

2023-11-13 14:36 UTC, merged